{% set name = "virtool" %}
{% set version = "2.3.2" %}
{% set sha256 = "230bc9b67bfa356b93e13d52d61a2da5ee9bb680d1077228176a356419137f5f" %}

package:
    name: "{{ name }}"
    version: "{{ version }}"

requirements:
    build:
        - nodejs >=6.11.5,<=9
        - python 3.6
    run:
        - skewer 0.2.2
        - certifi 2018.1.18
        - mongodb 3.4
        - hmmer 3.1b2
        - bowtie2 2.3.2
        - spades 3.8.1
        - numpy 1.15.1
        - python 3.6
        - aiofiles 0.3.2
        - aionotify 0.2.0
        - aiohttp 2.3.9
        - apipkg 1.4
        - appdirs 1.4.3
        - arrow 0.12.0
        - async-timeout 2.0.0
        - attrs 17.4.0
        - bcrypt 3.1.4
        - cchardet 2.1.1
        - Cerberus 1.1
        - cffi 1.11.4
        - chardet 3.0.4
        - coloredlogs 9.0
        - coverage 4.4.2
        - dictdiffer 0.7.0
        - execnet 1.5.0
        - humanfriendly 4.8
        - idna 2.6
        - idna_ssl 1.0.0
        - Mako 1.0.7
        - MarkupSafe 1.0
        - motor 1.2.1
        - multidict 4.0.0
        - nose 1.3.7
        - packaging 16.8
        - pluggy 0.6.0
        - psutil 5.4.3
        - py 1.5.2
        - pycparser 2.18
        - pyparsing 2.2.0
        - pytest 3.3.2
        - pytest-aiohttp 0.3.0
        - pytest-asyncio 0.8.0
        - pytest-cov 2.5.1
        - pytest-forked 0.2
        - pytest-mock 1.6.3
        - pytest-xdist 1.20.1
        - python-dateutil 2.6.1
        - raven 6.5.0
        - raven-aiohttp >=0.6.0
        - requests 2.18.4
        - semver 2.7.9
        - setproctitle 1.1.10
        - six 1.11.0
        - urllib3 1.22
        - uvloop 0.9.1
        - yarl 1.0.0
source:
    fn: "{{ name }}-{{ version }}.zip"
    url: "https://github.com/{{ name }}/{ name }}/archive/v{{ version }}.zip"
    sha256: "{{ sha256 }}"

build:
    number: 0
    skip: True # [not py36]

test:
    commands:
            - python $PREFIX/bin/run.py --help

about:
    summary: Virtool is a web-based application for diagnosing viral infections in plant samples using Illumina sequencing.
    home: https://www.virtool.ca/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    dev_url: https://github.com/virtool/virtool
    doc_url: https://www.virtool.ca/docs/

