#!/bin/bash

#need to know build number in order to access mongo stuff
#maybe we should put the database files for virtool into /share/mongo
#create an is_virtool_running function?

DATADIR="$CONDA_PREFIX/share/virtool"

if [ -z $MONGO_PORT ] ; then
  MONGO_PORT="27017"
fi
if [ -z $VIRTOOL_PORT] ; then
  VIRTOOL_PORT="9950"
fi

function main() {
  VIRTOOL_RUNNING="false"
  MONGOD_RUNNING="false"

  #check if virtool is already running
  if [ -e $DATADIR/virtool.pid ] && [ $( ps -ea | grep $( cat $DATADIR/virtool.pid ) | awk '{print $4}') == "virtool" ]; then
    VIRTOOL_RUNNING="true"
  else
    VIRTOOL_RUNNING="false"
  fi

  if [ -n "$1" ] ; then

    if [ "$1" = "on" ] ; then

      if [ $VIRTOOL_RUNNING = "true" ] ; then
        echo "virtool is already running \n" >&2
        exit 1
      fi

      virtool_start
      exit 0
    fi

    if [ "$1" = "off" ] ; then

      if [ "$VIRTOOL_RUNNING" = "false" ] ; then
        echo "virtool is not running already \n" >&2
        exit 1
      fi

      virtool_stop

	
      is_mongod_running
      if [ "$MONGOD_RUNNING" = "true" ] ; then
        mongod_stop
      fi

      exit 0
    fi

    echo "help goes here"
  fi
}

function is_mongod_running() {

  #check pid file
  if [ -e $DATADIR/mongo/mongo.pid ]  && [ $( ps -ea | grep $( cat $DATADIR/mongo/mongo.pid ) | awk '{print $4}') == "mongod" ]; then
    MONGOD_RUNNING="true"
  else
    MONGOD_RUNNING="false"
  fi
}

function mongod_start() {
  
  mongod --fork --pidfilepath $DATADIR/mongo/mongo.pid --logappend --logpath $DATADIR/mongo/mongo.log --dbpath $DATADIR/virtooldb --journal --port $MONGO_PORT
}

function mongod_stop() {
 
  kill -2 `cat $DATADIR/mongo/mongo.pid`
}

function virtool_start() {

  #check if mongod is running, make sure it is. loop X times until it starts?
  is_mongod_running
  if [ "$MONGOD_RUNNING" = "false" ] ; then
    mongod_start 
  fi

  #start virtool and setup pid
  python $CONDA_PREFIX/bin/run.py --port $VIRTOOL_PORT &
  echo $! > $DATADIR/virtool.pid
  VIRTOOL_RUNNING="true"
}

function virtool_stop() {

  #stop virtool and remove pid
  kill -2 `cat $DATADIR/virtool.pid`
  rm $DATADIR/virtool.pid
  VIRTOOL_RUNNING="false"
}

main "$@"

